### ISSUE TITLE
Crash with Croptopia fruits on 1.19.2

### ISSUE THREAD

**Issue by eliskvitka** [Oliver-makes-code/simple-right-click-harvest#1]
```
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{croptopia:apple_crop}
        at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.4)
        at net.minecraft.state.State.get(State:98)
        at com.github.olivermakescode.srch.SimpleHarvest.lambda$onInitialize$0(SimpleHarvest.java:29)
        at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
        at net.minecraft.client.network.ClientPlayerInteractionManager.handler$zim000$interactBlock(ClientPlayerInteractionManager:1185)
        at net.minecraft.client.network.ClientPlayerInteractionManager.interactBlock(ClientPlayerInteractionManager:327)
        at net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient:1748)
        at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:2002)
        at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1829)
        at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
        at net.minecraft.client.main.Main.main(Main:244)
        at net.minecraft.client.main.Main.main(Main:51)
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Oliver-makes-code** [comment]
I will look into this in a couple hours

**Comment by eliskvitka** [comment]
> I will look into this in a couple hours

I think it would be better just to skip such exceptions
